name: colordiff
channels:
  - conda-forge
  - pytorch
dependencies:
  - _ipython_minor_entry_point=8.7.0
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - comm=0.1.2
  - debugpy=1.6.4
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - ipykernel=6.19.4
  - ipython=8.7.0
  - jedi=0.18.2
  - jupyter_client=7.4.8
  - jupyter_core=5.1.0
  - ld_impl_linux-64=2.39
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - openssl=3.0.7
  - packaging=22.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - platformdirs=2.6.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.13.0
  - python=3.9.15
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=24.0.1
  - readline=8.1.2
  - setuptools=65.6.3
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.8.0
  - tzdata=2022g
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.2.6
  - zeromq=4.3.4
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==22.1.0
    - bashutils==0.0.4
    - beautifulsoup4==4.11.1
    - cachetools==5.2.0
    - certifi==2022.12.7
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colorama==0.4.6
    - contourpy==1.0.6
    - cycler==0.11.0
    - deepface==0.0.75
    - docker-pycreds==0.4.0
    - einops==0.6.0
    - einops-exts==0.0.3
    - ema-pytorch==0.1.2
    - fairscale==0.4.13
    - filelock==3.8.2
    - fire==0.5.0
    - flask==2.2.2
    - flatbuffers==22.12.6
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - gast==0.4.0
    - gdown==4.6.0
    - gitdb==4.0.10
    - gitpython==3.1.29
    - google-auth==2.15.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.51.1
    - h5py==3.7.0
    - helpers==0.2.0
    - icecream==2.1.3
    - idna==3.4
    - imageio==2.23.0
    - importlib-metadata==5.2.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - keras==2.11.0
    - kiwisolver==1.4.4
    - labml==0.4.161
    - labml-helpers==0.4.89
    - labml-nn==0.4.133
    - layers==0.1.5
    - libclang==14.0.6
    - lightning-utilities==0.4.2
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - mtcnn==0.1.1
    - multidict==6.0.3
    - networkx==2.8.8
    - numpy==1.24.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - pandas==1.5.2
    - pathtools==0.1.2
    - pillow==9.3.0
    - promise==2.3
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - pytorch-lightning==1.8.5.post0
    - pytz==2022.7
    - pywavelets==1.4.1
    - pyyaml==6.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - retina-face==0.0.12
    - rsa==4.9
    - scikit-image==0.19.3
    - scipy==1.9.3
    - sentry-sdk==1.12.1
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.29.0
    - termcolor==2.1.1
    - tifffile==2022.10.10
    - torch==1.13.1
    - torch-ema==0.3
    - torchinfo==1.7.1
    - torchmetrics==0.11.0
    - torchtext==0.14.1
    - torchvision==0.14.1
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - urllib3==1.26.13
    - wandb==0.13.7
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - yarl==1.8.2
    - zipp==3.11.0
